// This file is auto-generated by scripts/generate-mock-products.ts

export const scrapedItems = [
  {
    "link": "https://mock.spectrum.sahil.ink/product/84Z5Z4",
    "title": "EcoFriendly Water Bottle",
    "actualPrice": 27.11,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/CCT96M",
    "title": "Elite USB-C Charging Cable",
    "actualPrice": 19.05,
    "photoUrl": "https://placehold.co/300x300?text=Elite"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/DBN2LD",
    "title": "SmartChoice Portable Backpack",
    "actualPrice": 53.51,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/QWX358",
    "title": "SmartChoice Eco-Friendly Air Fryer",
    "actualPrice": 53.21,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/VJLN0T",
    "title": "QualityFirst Waterproof Gaming Headset",
    "actualPrice": 135.35,
    "photoUrl": "https://placehold.co/300x300?text=QualityFirst"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/UOETDW",
    "title": "FashionForward Wireless Bluetooth Headphones",
    "actualPrice": 120.34,
    "photoUrl": "https://placehold.co/300x300?text=FashionForward"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/KB3CIR",
    "title": "TechPro Watch",
    "actualPrice": 157.02,
    "photoUrl": "https://placehold.co/300x300?text=TechPro"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/XBOOYM",
    "title": "Generic Kitchen Knife Set",
    "actualPrice": 45.54,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/DO6APK",
    "title": "Premium Plant Pot",
    "actualPrice": 19.17,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/NFQ1B3",
    "title": "Premium Rechargeable Hoodie",
    "actualPrice": 76.58,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/W26S6S",
    "title": "Generic Wireless Bluetooth Headphones",
    "actualPrice": 122.03,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/JIK6C0",
    "title": "FashionForward Wireless Mouse",
    "actualPrice": 17.62,
    "photoUrl": "https://placehold.co/300x300?text=FashionForward"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/FYRPMF",
    "title": "BestValue USB-C Charging Cable",
    "actualPrice": 15.84,
    "photoUrl": "https://placehold.co/300x300?text=BestValue"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/YT45F4",
    "title": "EcoFriendly Eco-Friendly Handbag",
    "actualPrice": 116.24,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/ZIW9XI",
    "title": "Premium Portable Air Fryer",
    "actualPrice": 80.89,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/JI5KKN",
    "title": "EcoFriendly Rechargeable T-Shirt",
    "actualPrice": 30.33,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/79SRAN",
    "title": "Generic Plant Pot",
    "actualPrice": 19.66,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/ITL7X0",
    "title": "Generic Coffee Maker",
    "actualPrice": 94.43,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/5HE0IY",
    "title": "SmartChoice Coffee Maker",
    "actualPrice": 111.68,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/IHN9FD",
    "title": "HomeStyle Waterproof USB-C Charging Cable",
    "actualPrice": 22.74,
    "photoUrl": "https://placehold.co/300x300?text=HomeStyle"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/4NTX29",
    "title": "EcoFriendly Smart Watch",
    "actualPrice": 54.38,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/RYP3XW",
    "title": "FashionForward Portable Watch",
    "actualPrice": 117.48,
    "photoUrl": "https://placehold.co/300x300?text=FashionForward"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/OZYR42",
    "title": "SmartChoice Wireless Smartphone Case",
    "actualPrice": 39.55,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/1N257A",
    "title": "Elite Webcam",
    "actualPrice": 38.03,
    "photoUrl": "https://placehold.co/300x300?text=Elite"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/6WDYX1",
    "title": "FashionForward Bluetooth Gaming Headset",
    "actualPrice": 50.43,
    "photoUrl": "https://placehold.co/300x300?text=FashionForward"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/WDUI2C",
    "title": "FashionForward Plant Pot",
    "actualPrice": 10.23,
    "photoUrl": "https://placehold.co/300x300?text=FashionForward"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/8B21EF",
    "title": "EcoFriendly Rechargeable Sunglasses",
    "actualPrice": 33.91,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/A5DMOA",
    "title": "QualityFirst Waterproof Jacket",
    "actualPrice": 130.17,
    "photoUrl": "https://placehold.co/300x300?text=QualityFirst"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/I30VHY",
    "title": "Elite T-Shirt",
    "actualPrice": 35.5,
    "photoUrl": "https://placehold.co/300x300?text=Elite"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/PTYJKW",
    "title": "HomeStyle Bluetooth Throw Blanket",
    "actualPrice": 48.54,
    "photoUrl": "https://placehold.co/300x300?text=HomeStyle"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/5FH6UI",
    "title": "Premium Denim Jeans",
    "actualPrice": 93.55,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/MVSQ3C",
    "title": "QualityFirst Waterproof Hoodie",
    "actualPrice": 40.61,
    "photoUrl": "https://placehold.co/300x300?text=QualityFirst"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/ZPZ6UL",
    "title": "EcoFriendly Premium Handbag",
    "actualPrice": 106.87,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/2AVHWP",
    "title": "TechPro Yoga Mat",
    "actualPrice": 34.57,
    "photoUrl": "https://placehold.co/300x300?text=TechPro"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/DFJCY1",
    "title": "EcoFriendly Bluetooth Air Fryer",
    "actualPrice": 169.98,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/HPJ1MV",
    "title": "TechPro Compact Sneakers",
    "actualPrice": 45.5,
    "photoUrl": "https://placehold.co/300x300?text=TechPro"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/UNNBWB",
    "title": "Elite Backpack",
    "actualPrice": 81.65,
    "photoUrl": "https://placehold.co/300x300?text=Elite"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/BWZ5R3",
    "title": "Generic Handbag",
    "actualPrice": 82.71,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/KIVEF3",
    "title": "Premium Running Shoes",
    "actualPrice": 53.34,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/OUGQXC",
    "title": "Elite USB-C Charging Cable",
    "actualPrice": 23.2,
    "photoUrl": "https://placehold.co/300x300?text=Elite"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/NWV92D",
    "title": "TechPro USB-C Charging Cable",
    "actualPrice": 10.3,
    "photoUrl": "https://placehold.co/300x300?text=TechPro"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/QQ5LQ9",
    "title": "SmartChoice Premium T-Shirt",
    "actualPrice": 31.72,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/G3R3LQ",
    "title": "TechPro USB-C Charging Cable",
    "actualPrice": 20.95,
    "photoUrl": "https://placehold.co/300x300?text=TechPro"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/S15N92",
    "title": "TechPro Air Fryer",
    "actualPrice": 66.12,
    "photoUrl": "https://placehold.co/300x300?text=TechPro"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/JX6K6P",
    "title": "SmartChoice Bluetooth Speaker",
    "actualPrice": 90.02,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/GOXJ64",
    "title": "Premium Coffee Maker",
    "actualPrice": 90.05,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/GRQ6ZW",
    "title": "TechPro Eco-Friendly Water Bottle",
    "actualPrice": 21.04,
    "photoUrl": "https://placehold.co/300x300?text=TechPro"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/US6RGW",
    "title": "Premium Air Fryer",
    "actualPrice": 66.31,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/WU0QXC",
    "title": "SmartChoice USB-C Charging Cable",
    "actualPrice": 11.83,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/FM85TH",
    "title": "Premium Kitchen Knife Set",
    "actualPrice": 106.95,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/BG6BC6",
    "title": "SmartChoice Air Fryer",
    "actualPrice": 104.31,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/KL2C4U",
    "title": "BestValue Compact Kitchen Knife Set",
    "actualPrice": 28.09,
    "photoUrl": "https://placehold.co/300x300?text=BestValue"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/DBCLL9",
    "title": "Generic Plant Pot",
    "actualPrice": 25.69,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/S8MSWQ",
    "title": "EcoFriendly Wireless Wireless Mouse",
    "actualPrice": 40.18,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/A6S1NE",
    "title": "BestValue Smart Desk Lamp",
    "actualPrice": 43.11,
    "photoUrl": "https://placehold.co/300x300?text=BestValue"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/R4CU7Y",
    "title": "SmartChoice Wireless Throw Blanket",
    "actualPrice": 37.79,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/9TTWPW",
    "title": "Generic Eco-Friendly Kitchen Knife Set",
    "actualPrice": 57.98,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/1ELVM9",
    "title": "SmartChoice Throw Blanket",
    "actualPrice": 34.87,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/UVIISQ",
    "title": "Generic Eco-Friendly Watch",
    "actualPrice": 31.87,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/14JI8P",
    "title": "QualityFirst Throw Blanket",
    "actualPrice": 47.55,
    "photoUrl": "https://placehold.co/300x300?text=QualityFirst"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/YEXHCS",
    "title": "FashionForward Compact Denim Jeans",
    "actualPrice": 84.39,
    "photoUrl": "https://placehold.co/300x300?text=FashionForward"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/U77D68",
    "title": "BestValue Premium Wireless Bluetooth Headphones",
    "actualPrice": 117.26,
    "photoUrl": "https://placehold.co/300x300?text=BestValue"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/ULH9JT",
    "title": "Generic T-Shirt",
    "actualPrice": 35.32,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/5E2FFW",
    "title": "QualityFirst Water Bottle",
    "actualPrice": 32.48,
    "photoUrl": "https://placehold.co/300x300?text=QualityFirst"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/ODJTMH",
    "title": "Premium Smart Mechanical Keyboard",
    "actualPrice": 54.21,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/US3W12",
    "title": "TechPro Backpack",
    "actualPrice": 72.23,
    "photoUrl": "https://placehold.co/300x300?text=TechPro"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/894MEI",
    "title": "BestValue Protein Powder",
    "actualPrice": 31.76,
    "photoUrl": "https://placehold.co/300x300?text=BestValue"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/1WCVX0",
    "title": "BestValue Desk Lamp",
    "actualPrice": 76.04,
    "photoUrl": "https://placehold.co/300x300?text=BestValue"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/8AHLA5",
    "title": "SmartChoice Sneakers",
    "actualPrice": 114.66,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/EUYKQW",
    "title": "HomeStyle Compact Plant Pot",
    "actualPrice": 18.29,
    "photoUrl": "https://placehold.co/300x300?text=HomeStyle"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/CYYJZU",
    "title": "HomeStyle Protein Powder",
    "actualPrice": 31.08,
    "photoUrl": "https://placehold.co/300x300?text=HomeStyle"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/DL6VT6",
    "title": "Generic T-Shirt",
    "actualPrice": 29.06,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/77WALD",
    "title": "BestValue Waterproof Running Shoes",
    "actualPrice": 65.33,
    "photoUrl": "https://placehold.co/300x300?text=BestValue"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/V6B06V",
    "title": "SmartChoice Wireless Mouse",
    "actualPrice": 57.96,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/I9SGOB",
    "title": "EcoFriendly Compact Kitchen Knife Set",
    "actualPrice": 75.28,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/EG1X9R",
    "title": "QualityFirst Compact Water Bottle",
    "actualPrice": 29.25,
    "photoUrl": "https://placehold.co/300x300?text=QualityFirst"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/9M1T2G",
    "title": "Generic Portable Denim Jeans",
    "actualPrice": 47.33,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/FBQ9C9",
    "title": "FashionForward Portable Sunglasses",
    "actualPrice": 44.1,
    "photoUrl": "https://placehold.co/300x300?text=FashionForward"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/KO1CR8",
    "title": "TechPro Handbag",
    "actualPrice": 57.57,
    "photoUrl": "https://placehold.co/300x300?text=TechPro"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/YVD4Z1",
    "title": "Premium Hoodie",
    "actualPrice": 42.16,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/J53Q52",
    "title": "HomeStyle Bluetooth Hoodie",
    "actualPrice": 74.92,
    "photoUrl": "https://placehold.co/300x300?text=HomeStyle"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/UTN1BY",
    "title": "HomeStyle Kitchen Knife Set",
    "actualPrice": 46.19,
    "photoUrl": "https://placehold.co/300x300?text=HomeStyle"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/73N432",
    "title": "QualityFirst Eco-Friendly Wireless Bluetooth Headphones",
    "actualPrice": 150.37,
    "photoUrl": "https://placehold.co/300x300?text=QualityFirst"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/ITXPJ3",
    "title": "BestValue Professional Denim Jeans",
    "actualPrice": 80.17,
    "photoUrl": "https://placehold.co/300x300?text=BestValue"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/JLBWX3",
    "title": "BestValue Handbag",
    "actualPrice": 46.26,
    "photoUrl": "https://placehold.co/300x300?text=BestValue"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/SN53P5",
    "title": "SmartChoice Waterproof Watch",
    "actualPrice": 123.08,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/35O3FI",
    "title": "SmartChoice Premium Plant Pot",
    "actualPrice": 37.06,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/8M3H9U",
    "title": "TechPro Smart Tablet Stand",
    "actualPrice": 16.68,
    "photoUrl": "https://placehold.co/300x300?text=TechPro"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/A0P9HZ",
    "title": "HomeStyle Eco-Friendly Plant Pot",
    "actualPrice": 30.83,
    "photoUrl": "https://placehold.co/300x300?text=HomeStyle"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/0IN6E7",
    "title": "BestValue Compact Sunglasses",
    "actualPrice": 40.96,
    "photoUrl": "https://placehold.co/300x300?text=BestValue"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/V97WLQ",
    "title": "Premium USB-C Charging Cable",
    "actualPrice": 22.81,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/EL1MHJ",
    "title": "EcoFriendly Bluetooth Dress",
    "actualPrice": 59.56,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/638GLW",
    "title": "Premium Backpack",
    "actualPrice": 77.78,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/T689ZS",
    "title": "QualityFirst Dress",
    "actualPrice": 68.68,
    "photoUrl": "https://placehold.co/300x300?text=QualityFirst"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/26IGPN",
    "title": "FashionForward Portable Kitchen Knife Set",
    "actualPrice": 112.72,
    "photoUrl": "https://placehold.co/300x300?text=FashionForward"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/HCWQHU",
    "title": "SmartChoice Smart Air Fryer",
    "actualPrice": 126.86,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/V060MV",
    "title": "EcoFriendly Wireless Bluetooth Headphones",
    "actualPrice": 50.91,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/YJ378A",
    "title": "TechPro Rechargeable Mechanical Keyboard",
    "actualPrice": 108.12,
    "photoUrl": "https://placehold.co/300x300?text=TechPro"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/S53TLP",
    "title": "TechPro Smartphone Case",
    "actualPrice": 35.13,
    "photoUrl": "https://placehold.co/300x300?text=TechPro"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/CU8PX2",
    "title": "EcoFriendly Waterproof Water Bottle",
    "actualPrice": 13,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/TFGFUQ",
    "title": "FashionForward Watch",
    "actualPrice": 120.7,
    "photoUrl": "https://placehold.co/300x300?text=FashionForward"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/ULA1C4",
    "title": "FashionForward Tablet Stand",
    "actualPrice": 17.26,
    "photoUrl": "https://placehold.co/300x300?text=FashionForward"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/VOOHXD",
    "title": "QualityFirst Tablet Stand",
    "actualPrice": 16.92,
    "photoUrl": "https://placehold.co/300x300?text=QualityFirst"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/UHRN38",
    "title": "SmartChoice Compact Sneakers",
    "actualPrice": 63.59,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/0J2S8N",
    "title": "TechPro Premium Tablet Stand",
    "actualPrice": 25.34,
    "photoUrl": "https://placehold.co/300x300?text=TechPro"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/P24Q86",
    "title": "Generic Professional T-Shirt",
    "actualPrice": 25.17,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/S6WRAU",
    "title": "BestValue Smart Plant Pot",
    "actualPrice": 27.39,
    "photoUrl": "https://placehold.co/300x300?text=BestValue"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/1R9S7L",
    "title": "FashionForward Portable USB-C Charging Cable",
    "actualPrice": 21.3,
    "photoUrl": "https://placehold.co/300x300?text=FashionForward"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/K7GWBM",
    "title": "EcoFriendly Jacket",
    "actualPrice": 50.26,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/03JNG6",
    "title": "Generic Bluetooth Sunglasses",
    "actualPrice": 34.28,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/CP0144",
    "title": "Generic Rechargeable Throw Blanket",
    "actualPrice": 42.37,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/AOWBBQ",
    "title": "BestValue Handbag",
    "actualPrice": 85.71,
    "photoUrl": "https://placehold.co/300x300?text=BestValue"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/YU9LHH",
    "title": "QualityFirst Coffee Maker",
    "actualPrice": 98.64,
    "photoUrl": "https://placehold.co/300x300?text=QualityFirst"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/NF3YPV",
    "title": "Elite Running Shoes",
    "actualPrice": 85.84,
    "photoUrl": "https://placehold.co/300x300?text=Elite"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/NHUN36",
    "title": "FashionForward Backpack",
    "actualPrice": 75.38,
    "photoUrl": "https://placehold.co/300x300?text=FashionForward"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/QOR6PM",
    "title": "BestValue Portable Air Fryer",
    "actualPrice": 102.52,
    "photoUrl": "https://placehold.co/300x300?text=BestValue"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/07AIUR",
    "title": "EcoFriendly Portable Yoga Mat",
    "actualPrice": 37.62,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/70JK2F",
    "title": "SmartChoice Premium Yoga Mat",
    "actualPrice": 22.79,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/4IORH1",
    "title": "Premium Wireless Denim Jeans",
    "actualPrice": 60.34,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/K4U0GC",
    "title": "QualityFirst Wireless USB-C Charging Cable",
    "actualPrice": 11.45,
    "photoUrl": "https://placehold.co/300x300?text=QualityFirst"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/22VX9L",
    "title": "HomeStyle Dress",
    "actualPrice": 50.74,
    "photoUrl": "https://placehold.co/300x300?text=HomeStyle"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/HAPUY4",
    "title": "Premium Bluetooth Sneakers",
    "actualPrice": 108.46,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/K7O4CI",
    "title": "Generic Wireless Mouse",
    "actualPrice": 41.36,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/B0ZRN0",
    "title": "EcoFriendly Denim Jeans",
    "actualPrice": 84.49,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/KUXKAN",
    "title": "EcoFriendly Compact Watch",
    "actualPrice": 85.44,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/ADYP84",
    "title": "EcoFriendly Premium USB-C Charging Cable",
    "actualPrice": 10.16,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/QQ1GYJ",
    "title": "HomeStyle Wireless Sneakers",
    "actualPrice": 50.79,
    "photoUrl": "https://placehold.co/300x300?text=HomeStyle"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/DNQJXB",
    "title": "Premium Sneakers",
    "actualPrice": 92.59,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/TR0SM1",
    "title": "Generic Smart Desk Lamp",
    "actualPrice": 34.69,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/4F3QXU",
    "title": "SmartChoice Wireless Bluetooth Speaker",
    "actualPrice": 97.68,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/CKCY59",
    "title": "SmartChoice Webcam",
    "actualPrice": 88.51,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/8EWSX5",
    "title": "Generic Denim Jeans",
    "actualPrice": 87.86,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/S5HFLS",
    "title": "Generic Premium Jacket",
    "actualPrice": 114.19,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/RZEG7F",
    "title": "Elite Premium Dress",
    "actualPrice": 40.59,
    "photoUrl": "https://placehold.co/300x300?text=Elite"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/WI50J2",
    "title": "SmartChoice Sunglasses",
    "actualPrice": 38.2,
    "photoUrl": "https://placehold.co/300x300?text=SmartChoice"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/CVK3A4",
    "title": "EcoFriendly Professional USB-C Charging Cable",
    "actualPrice": 20.98,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/NKONQD",
    "title": "HomeStyle Gaming Headset",
    "actualPrice": 79.41,
    "photoUrl": "https://placehold.co/300x300?text=HomeStyle"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/1A6N8Q",
    "title": "EcoFriendly T-Shirt",
    "actualPrice": 35.52,
    "photoUrl": "https://placehold.co/300x300?text=EcoFriendly"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/CZHHKG",
    "title": "QualityFirst Rechargeable Wireless Mouse",
    "actualPrice": 25.24,
    "photoUrl": "https://placehold.co/300x300?text=QualityFirst"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/9UZDXC",
    "title": "Premium Premium Backpack",
    "actualPrice": 93.34,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/NBQPY1",
    "title": "TechPro Smart Wireless Bluetooth Headphones",
    "actualPrice": 79.19,
    "photoUrl": "https://placehold.co/300x300?text=TechPro"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/JKB9BB",
    "title": "TechPro Wireless Portable Power Bank",
    "actualPrice": 56.43,
    "photoUrl": "https://placehold.co/300x300?text=TechPro"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/SEA5X1",
    "title": "FashionForward Wireless Dress",
    "actualPrice": 85.55,
    "photoUrl": "https://placehold.co/300x300?text=FashionForward"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/2HBQR4",
    "title": "HomeStyle Professional Kitchen Knife Set",
    "actualPrice": 32.88,
    "photoUrl": "https://placehold.co/300x300?text=HomeStyle"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/6F3KZU",
    "title": "Generic Waterproof Wireless Bluetooth Headphones",
    "actualPrice": 141.59,
    "photoUrl": "https://placehold.co/300x300?text=Generic"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/PES9AM",
    "title": "FashionForward Handbag",
    "actualPrice": 63.8,
    "photoUrl": "https://placehold.co/300x300?text=FashionForward"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/EFIT8T",
    "title": "Premium Sunglasses",
    "actualPrice": 33.28,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/GTO5UO",
    "title": "Premium Rechargeable Watch",
    "actualPrice": 128.8,
    "photoUrl": "https://placehold.co/300x300?text=Premium"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/ARWXNE",
    "title": "BestValue Rechargeable Webcam",
    "actualPrice": 31.68,
    "photoUrl": "https://placehold.co/300x300?text=BestValue"
  },
  {
    "link": "https://mock.spectrum.sahil.ink/product/QXJNNK",
    "title": "TechPro Mechanical Keyboard",
    "actualPrice": 151.55,
    "photoUrl": "https://placehold.co/300x300?text=TechPro"
  }
] as const;
